name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  hyperlink: ^0.0.4
  provider: ^6.1.1
  firebase_core: ^3.0.0
  firebase_database: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.3.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/items.json